name: "Generate References"

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Package name to generate references for'
        required: true
        type: string

jobs:
  generate-references:
    name: Generate SDK references
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          build: false

      - name: Build packages
        run: pnpm build
        
      - name: Generate SDK references
        run: turbo --filter="${{ github.event.inputs.package_name }}" generate-references

      - name: Check for changes in references
        id: changes
        run: |
          PACKAGE_DIR="packages/${{ github.event.inputs.package_name }}/references/"
          if [ -n "$(git status --porcelain "$PACKAGE_DIR")" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "New references generated for ${{ github.event.inputs.package_name }}:"
            git status --porcelain "$PACKAGE_DIR"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No new references generated for ${{ github.event.inputs.package_name }}"
          fi
      - uses: stefanzweifel/git-auto-commit-action@b3e3f72439fc3af08948f989a19a825463598a
        if: steps.changes.outputs.changed == 'true'
        with:
          commit_message: "Update generated references"
          file_pattern: "packages/*/references/**"