name: "Release"

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: posthog-react-native
          - name: posthog-node
          - name: posthog-js-lite
          - name: posthog-js
          - name: "@posthog/core"
          - name: "@posthog/react"
          - name: "@posthog/ai"
          - name: "@posthog/nextjs-config"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          install: false
          build: false

      - name: Get package path
        id: get-package-path
        run: |
          PACKAGE_PATH=$(pnpm list --filter=${{ matrix.package.name }} --json | jq -r '.[0].path')
          echo "path=$PACKAGE_PATH" >> "$GITHUB_OUTPUT"

      - name: Check ${{ matrix.package.name }} version and detect an update
        id: check-package-version
        uses: PostHog/check-package-version@v2.1.0
        with:
          path: ${{ steps.get-package-path.outputs.path }}


      - name: Generate references for ${{ matrix.package.name }}
        if: steps.check-package-version.outputs.is-new-version == 'true'
        continue-on-error: true
        run: |
          curl -f -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/posthog/posthog-js/actions/workflows/generate-references.yml/dispatches \
               -d '{
                 "ref": "main",
                 "inputs": {
                   "package_name": "${{ matrix.package.name }}"
                 }
               }'
